const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike.slim-shirt',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 500,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: 'images/p2.jpg',
      price: 600,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Nike Slim Pants',
      slug: 'nike.slim-pants',
      category: 'Pants',
      image: 'images/p3.jpg',
      price: 300,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'High quality pants',
    },
    {
      name: 'Adidas Fit Pants',
      slug: 'adidas-fit-pants',
      category: 'pants',
      image: 'images/p4.jpg',
      price: 300,
      countInStock: 6,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
};

export default data;
